import re
import spacy

class FeatureExtractor:
    def __init__(self):
        # Load the small English pipeline for Named Entity Recognition (NER)
        try:
            self.nlp = spacy.load("en_core_web_sm")
        except OSError:
            # Fallback handling if model is not linked properly
            raise OSError("spaCy model 'en_core_web_sm' not found. Please run: python -m spacy download en_core_web_sm")

    def extract_regex_features(self, text):
        """Extracts boolean flags for specific sensitive patterns using Regex"""
        features = {}
        
        # 1. Sri Lankan National Identity Card (NIC) pattern matching (Old and New formats)
        nic_pattern = r'\b([0-9]{9}[vVxX]|[0-9]{12})\b'
        features['has_nic'] = 1 if re.search(nic_pattern, text) else 0
        
        # 2. Credit Card number pattern matching
        card_pattern = r'\b(?:\d[ -]*?){13,16}\b'
        features['has_credit_card'] = 1 if re.search(card_pattern, text) else 0
        
        # 3. Phone number pattern matching (Generic and local formats)
        phone_pattern = r'\b(?:\+?94|0)[7-9][0-9]{8}\b|\b(?:\+?1[-. ]?)?\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})\b'
        features['has_phone'] = 1 if re.search(phone_pattern, text) else 0
        
        return features

    def extract_ner_counts(self, text):
        """Counts occurrence of critical named entities using spaCy NER"""
        if not text:
            return {"count_person": 0, "count_org": 0, "count_gpe": 0}
            
        doc = self.nlp(text)
        person_count = 0
        org_count = 0
        gpe_count = 0 # GPE: Countries, Cities, States
        
        for ent in doc.ents:
            if ent.label_ == "PERSON":
                person_count += 1
            elif ent.label_ == "ORG":
                org_count += 1
            elif ent.label_ == "GPE":
                gpe_count += 1
                
        return {
            "count_person": person_count,
            "count_org": org_count,
            "count_gpe": gpe_count
        }

    def get_combined_features(self, text):
        """Combines both Regex flags and NER counts into a single dictionary"""
        regex_feats = self.extract_regex_features(text)
        ner_feats = self.extract_ner_counts(text)
        
        # Merge both dictionaries
        combined = {**regex_feats, **ner_feats}
        return combined

if __name__ == "__main__":
    # Test script block with a sensitive sample document text
    extractor = FeatureExtractor()
    sample_sensitive_text = (
        "Project Report generated by John Doe from SLTC. "
        "Manager contact details: +94771234567. "
        "Verification ID card number is 200211403456."
    )
    
    features = extractor.get_combined_features(sample_sensitive_text)
    print("--- Extracted Metadata Features ---")
    for key, value in features.items():
        print(f"{key}: {value}")